#!/bin/bash

set -euo pipefail

indice_extendido=".index-extended"
indice=".index"

for file in ./*.so; do
    if [[ -f "$file" ]]; then
        nombre_archivo=$(basename "$file" .so)
        fecha_actual=$(date +%Y-%m-%d)
        nombre_zip="${nombre_archivo}.so.zip"

        # Comprimir solo el archivo .so en un archivo zip
        zip "$nombre_zip" "$nombre_archivo.so" "$nombre_archivo.info"

        # Calcular CRC32 del archivo zip
        comprobacion=$(crc32 "$nombre_zip")

        # Generar el nombre para el archivo de índice
        indice_nuevo="${fecha_actual} ${comprobacion} ${nombre_zip}"

        # Actualizar índices
        sed -i "s/^.*$nombre_zip.*$/$indice_nuevo/" "$indice_extendido"
		if ! grep -q "$nombre_zip" "$indice"; then
        sed -i "/$nombre_zip/d" "$indice"
        echo "$nombre_zip" >> "$indice"
		fi

        # Eliminar archivo .so original
        rm "$file"

        echo "Archivo $nombre_archivo.so comprimido e indexado como $indice_nuevo"
    fi
done