#!/bin/sh
# To run /etc/init.d/S* script
for deinitscript in /etc/init.d/K[0-9][0-9]*
do
	if [ -x $deinitscript ] ;
	then
		echo "[start] $deinitscript"
		$deinitscript
		echo "[End] $deinitscript"
	fi
done
