name: Issue Report
description: Create a report to help us improve Koriki
assignees:
  - eduardofilo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report.

        Before creating the issue, follow these steps:

        1. Check the [FAQ](https://github.com/Rparadise-Team/Koriki/blob/main/wiki/05.en.faq.md) and [Problem solving](https://github.com/Rparadise-Team/Koriki/blob/main/wiki/04.en.problem_solving.md) documents on the wiki to see if the problem you observed is already solved or has a known workaround.
        2. If it is more of a question than a problem, consider opening a [Discussion](https://github.com/Rparadise-Team/Koriki/discussions) post instead of opening an Issue.
        3. Think about whether the issue is with the distribution itself or with one of the pieces of software it contains (SimpleMenu, RetroArch, Apps).
        4. The software contained in the distribution is mostly homebrew and not perfect. Consider whether your request makes sense considering the situation.
        5. The distribution brings together the work of many people who have put in many hours of effort. If you encounter an issue that you have the capacity to solve on your own, consider taking some time to contribute with the solution to the collective work.

        In case of doubt about the version of the distribution being used, you can find out by mean of `System Info` app or viewing the contents of the file `/mnt/SDCARD/Koriki/version.txt`
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the issue is.
      placeholder: Tell us what you see
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: On which version did you observe the issue?
      options:
        - v1.0
    validations:
      required: true
