#!/bin/sh

export SCREEN_WIDTH=640
export SCREEN_HEIGHT=480
export SDCARD_PATH=/mnt/SDCARD
export HOME=${SDCARD_PATH}

export SYSTEM_PATH=${SDCARD_PATH}/Koriki
export CUSTOMER_DIR=/customer

export LD_LIBRARY_PATH="${SYSTEM_PATH}/lib/sdl2.0:${SYSTEM_PATH}/lib:${LD_LIBRARY_PATH}"
export PATH="${SYSTEM_PATH}/bin:${PATH}"

export SWAPFILE=/mnt/SDCARD/cachefile


killprocess() {
   pid=`ps | grep $1 | grep -v grep | cut -d' ' -f3`
   kill -9 $pid
}

init_lcd() {
   cat /proc/ls
   if [ $1 -ne 0 ] ; then
	sleep $1
   fi 
}

runifnecessary() {
    a=`ps | grep $1 | grep -v grep`
    if [ "$a" == "" ] ; then
        $2 &
    fi
}

reset_settings() {
    if [ -f ${SDCARD_PATH}/.reset_settings ]; then
        cp ${SYSTEM_PATH}/assets/system.json /appconfigs/system.json
        rm ${SDCARD_PATH}/.reset_settings
        sync
    fi
}

update() {
    if [ -f ${SDCARD_PATH}/update_koriki_*.zip ]; then
        for file in `ls ${SDCARD_PATH}/update_koriki_*.zip`; do
            unzip -o ${file} .update_splash.png -d ${SDCARD_PATH}
            sync
            ${SYSTEM_PATH}/bin/show ${SDCARD_PATH}/.update_splash.png

            unzip -o ${file} .deletes -d ${SDCARD_PATH}
            if [ -f ${SDCARD_PATH}/.deletes ]; then
                while read file_to_delete; do
                    rm -rf "${file_to_delete}"
                done < ${SDCARD_PATH}/.deletes
            fi

            unzip -o ${file} -d ${SDCARD_PATH}

            rm ${file}
            sleep 5s
        done
    fi
    if [ -f ${SDCARD_PATH}/.deletes ]; then
        rm ${SDCARD_PATH}/.deletes
    fi
    if [ -f ${SDCARD_PATH}/.update_splash.png ]; then
        rm ${SDCARD_PATH}/.update_splash.png
    fi
}


# Reset settings on first boot
reset_settings

# Init_lcd
init_lcd 1

# Init charger GPIO
if [ ! -f /sys/devices/gpiochip0/gpio/gpio59/direction ]; then
    echo 59 > /sys/class/gpio/export
    echo in > /sys/devices/gpiochip0/gpio/gpio59/direction
fi

# Init backlight
echo 0 > /sys/class/pwm/pwmchip0/export
echo 800 > /sys/class/pwm/pwmchip0/pwm0/period
echo 70 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable

# Charging screen
${SYSTEM_PATH}/bin/charging

# Update opportunity
update

# Show bootScreen
${SYSTEM_PATH}/bin/show ${SDCARD_PATH}/Koriki/images/bootScreen.png

# Enable swap
if [ ! -f ${SWAPFILE} ]; then
    dd if=/dev/zero of=${SWAPFILE} bs=1M count=128
    mkswap ${SWAPFILE}
fi
swapon ${SWAPFILE}

# Koriki keymon
runifnecessary "keymon" ${SYSTEM_PATH}/bin/keymon

# Detect 'B' press to fix SM boot loops
if cat /sys/kernel/debug/gpio|grep gpio-6|grep lo > /dev/null 2>&1
then
    rm ${SDCARD_PATH}/.simplemenu/last_state.sav
fi

# Latency reduction audioserver by Eggs
# NOTE: could cause performance issues on more demanding cores...maybe?
runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
    if [ -f /customer/lib/libpadsp.so ]; then
        LD_PRELOAD=as_preload.so audioserver.mod &
        export LD_PRELOAD=libpadsp.so
    fi
fi

# Launch SimpleMenu
while [ 1 ]; do
    HOME=${SDCARD_PATH}
    cd ${SDCARD_PATH}/.simplemenu
    ./simplemenu
    sleep 4s
done

reboot