#!/bin/sh

source_dir="/mnt/SDCARD/Saves/RA_saves/TGB Dual/.netplay"
destination_dir="/mnt/SDCARD/Saves/RA_saves/TGB Dual"
gambatte_dir="/mnt/SDCARD/Saves/RA_saves/Gambatte"
tgb_dual_config="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.opt"
tgb_dual_config_p1="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.p1"
backup_config="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.backup"

show /mnt/SDCARD/App/gb_server/screen.png &

if [ ! -f "$backup_config" ]; then
    cp "$tgb_dual_config" "$backup_config"
    cp "$tgb_dual_config_p1" "$tgb_dual_config"
    sync
fi

game1_name=$(basename "$1" | sed 's/\.[^.]*$//')
game2_name=$(basename "$2" | sed 's/\.[^.]*$//')

if [ ! -f "$gambatte_dir"/"$game1_name".srm ]; then
	touch "$gambatte_dir"/"$game1_name".srm
fi

if [ ! -f "$gambatte_dir"/"$game1_name".rtc ]; then
	touch "$gambatte_dir"/"$game1_name".rtc
fi

if [ ! -f "$gambatte_dir"/"$game2_name".srm ]; then
	touch "$gambatte_dir"/"$game2_name".srm
fi

if [ ! -f "$gambatte_dir"/"$game2_name".rtc ]; then
	touch "$gambatte_dir"/"$game2_name".rtc
fi

cp "$gambatte_dir"/"$game1_name".srm "$destination_dir"/"$game1_name".srm
cp "$gambatte_dir"/"$game1_name".rtc "$destination_dir"/"$game1_name".rtc
cp "$gambatte_dir"/"$game2_name".srm "$destination_dir"/"$game2_name".srm
cp "$gambatte_dir"/"$game2_name".rtc "$destination_dir"/"$game2_name".rtc

cp "$destination_dir"/"$game1_name".srm "$destination_dir"/0server-"$game1_name".srm
cp "$destination_dir"/"$game1_name".rtc "$destination_dir"/0server-"$game1_name".rtc

sync

GET1="/tmp/0client-"$game2_name".srm"
GET2="/tmp/0client-"$game2_name".rtc"
DONEFILE="/tmp/donefile"

bftpd -c /mnt/SDCARD/App/gb_server/bftpd.conf -D &

sleep 2

max_attempts=40
attempts_left=$max_attempts

while [ $attempts_left -gt 0 ]; do
	if [ -f "$GET1" ] && [ -f "$GET2" ]; then
       	break
    elif [ $attempts_left -eq 1 ]; then
		killall bftpd
		pkill -TERM show
		show /mnt/SDCARD/App/gb_client/screenfail.png &
		
		rm -f "$destination_dir"/0client-*
		rm -f "$destination_dir"/0server-*
		rm -rf "$source_dir"
		sync
		
		cp "$backup_config" "$tgb_dual_config"
		rm "$backup_config"
		sync
		
		sleep 4
		pkill -TERM show
       	exit 1
    elif [ $attempts_left -gt 1 ]; then
       	attempts_left=$((attempts_left - 1))
       	sleep 1
    fi
done

if [ ! -f "$GET1" ] || [ ! -f "$GET2" ]; then
	killall bftpd
	pkill -TERM show
	show /mnt/SDCARD/App/gb_client/screenfail.png &
			
	rm -f "$destination_dir"/0client-*
	rm -f "$destination_dir"/0server-*
	rm -rf "$source_dir"
	sync
	
	cp "$backup_config" "$tgb_dual_config"
	rm "$backup_config"
	sync
		
	sleep 4
	pkill -TERM show
   	exit 1
fi

touch "$DONEFILE"
sync

sleep 2

killall bftpd

cp "$GET1" "$destination_dir"/0client-"$game2_name".srm
cp "$GET2" "$destination_dir"/0client-"$game2_name".rtc

sync

game1_name_rom=$(basename "$1")
game2_name_rom=$(basename "$2")

if [ "${1##*.}" = "gb" ] && [ "${2##*.}" = "gb" ]; then
    roms_directory="/mnt/SDCARD/Roms/GB"
elif [ "${1##*.}" = "gb" ] && [ "${2##*.}" = "gbc" ]; then
    roms_directory="/mnt/SDCARD/Roms/GB"
elif [ "${1##*.}" = "gbc" ] && [ "${2##*.}" = "gb" ]; then
    roms_directory="/mnt/SDCARD/Roms/GBC"
elif [ "${1##*.}" = "gbc" ] && [ "${2##*.}" = "gbc" ]; then
    roms_directory="/mnt/SDCARD/Roms/GBC"
fi

server_file="$roms_directory""/0server-""$game1_name_rom"
client_file="$roms_directory""/0client-""$game2_name_rom"

cp "$1" "$server_file"

cp "$2" "$client_file"

sync

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/

runsvr=`/customer/app/jsonval audiofix`

pkill -TERM show

if [ "$runsvr" != "0" ] ; then
    LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so /mnt/SDCARD/RetroArch/retroarch -H -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/tgbdual_libretro.so --subsystem "gb_link_2p" "$server_file" "$client_file"
else
    /mnt/SDCARD/RetroArch/retroarch -H -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/tgbdual_libretro.so --subsystem "gb_link_2p" "$server_file" "$client_file"
fi

rm -f "$destination_dir"/0client-*

cp "$destination_dir"/0server-*.srm "$destination_dir"/"$game1_name".srm
cp "$destination_dir"/0server-*.rtc "$destination_dir"/"$game1_name".rtc

cp "$destination_dir"/"$game1_name".srm "$gambatte_dir"/"$game1_name".srm
cp "$destination_dir"/"$game1_name".rtc "$gambatte_dir"/"$game1_name".rtc

rm -f "$destination_dir"/0server-*

rm -rf "$source_dir"
sync

cp "$backup_config" "$tgb_dual_config"
rm "$backup_config"
sync

rm -f "$server_file"
rm -f "$client_file"
rm -f "$GET1"
rm -f "$GET2"
rm -f "$DONEFILE"
sync
