#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`
cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
RA_CONFIG=/mnt/SDCARD/RetroArch/.retroarch/retroarch.cfg

if [ "$runsvr" != "0" ]; then
    sed -i 's/^video_vsync = "false"/video_vsync = "true"/' "$RA_CONFIG"
else
    sed -i 's/^video_vsync = "true"/video_vsync = "false"/' "$RA_CONFIG"
fi

if [ "$runsvr" != "0" ] ; then
LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/fake08_libretro.so "$1"
else
nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/fake08_libretro.so "$1"
fi
