#!/bin/sh

killall audioserver
killall audioserver.min
killall audioserver.plu

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/ /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/fbalpha2012_cps3_libretro.so "$1"

runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
    LD_PRELOAD=/mnt/SDCARD/Koriki/lib/as_preload.so /mnt/SDCARD/Koriki/bin/audioserver > /dev/null 2>&1 &
    if [ -f /customer/lib/libpadsp.so ]; then
        export LD_PRELOAD=/customer/lib/libpadsp.so
    fi
fi
