#!/bin/sh
cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/

# sav to srm

for file in /mnt/SDCARD/Saves/RA_saves/gpSP/*.sav; do
    if [ -e "$file" ]; then
        cp "$file" "${file%.sav}.srm"
    fi
done

rm /mnt/SDCARD/Saves/RA_saves/gpSP/*.sav

runsvr=`/customer/app/jsonval audiofix`

if [ "$runsvr" != "0" ] ; then
LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/gpsp_plus_libretro.so "$1"
else
nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/gpsp_plus_libretro.so "$1"
fi
