#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`
cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
RA_CONFIG=/mnt/SDCARD/RetroArch/.retroarch/retroarch.cfg

AUDIO_DRIVER=$(grep "^audio_driver" "$RA_CONFIG" | cut -d'"' -f2)

sed -i 's/^audio_driver = ".*"/audio_driver = "audioio"/' "$RA_CONFIG"


if [ "$runsvr" != "0" ] ; then
LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/mgba_plus_libretro.so "$1"
else
/mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/mgba_plus_libretro.so "$1"
fi

sed -i "s/^audio_driver = \"audioio\"/audio_driver = \"$AUDIO_DRIVER\"/" "$RA_CONFIG"
sync