#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`

if [ "$runsvr" != "0" ] ; then
	FILE=/customer/app/axp_test
	
	if [ -f /customer/lib/libpadsp.so ]; then
		unset LD_PRELOAD
	fi
	
    if [ -f "$FILE" ]; then
        killall audioserver
		killall audioserver.plu
		FILE2=/tmp/audioserver_on
		if [ -f "$FILE2" ]; then
			rm /tmp/audioserver_on
			/mnt/SDCARD/Koriki/bin/freemma
		fi
    else
        killall audioserver
		killall audioserver.min
    fi
fi

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
/mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/pcsx_rearmed_libretro.so "$1"

runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
	FILE=/customer/app/axp_test
	if [ -f "$FILE" ]; then
	touch /tmp/audioserver_on
	fi
	/mnt/SDCARD/Koriki/bin/audioserver &
	if [ -f /customer/lib/libpadsp.so ]; then
		export LD_PRELOAD=/customer/lib/libpadsp.so
	fi
fi

echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
