#!/bin/sh
runsvr=`/customer/app/jsonval audiofix`
cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
RA_CONFIG=/mnt/SDCARD/RetroArch/.retroarch/retroarch.cfg

destination_dir="/mnt/SDCARD/Saves/RA_saves/TGB Dual"
gambatte_dir="/mnt/SDCARD/Saves/RA_saves/Gambatte"

game_name=$(basename "$1" | sed 's/\.[^.]*$//')

if [ -f "$gambatte_dir"/"$game_name".srm ]; then
	cp "$gambatte_dir"/"$game_name".srm "$destination_dir"/"$game_name".srm
	sync
fi

if [ -f "$gambatte_dir"/"$game_name".rtc ]; then
	cp "$gambatte_dir"/"$game_name".rtc "$destination_dir"/"$game_name".rtc
	sync
fi

if [ "$runsvr" != "0" ]; then
    sed -i 's/^video_vsync = "false"/video_vsync = "true"/' "$RA_CONFIG"
else
    sed -i 's/^video_vsync = "true"/video_vsync = "false"/' "$RA_CONFIG"
fi

if [ "$runsvr" != "0" ] ; then
LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/tgbdual_libretro.so "$1"
else
nice -n -20  /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/tgbdual_libretro.so "$1"
fi

cp "$destination_dir"/"$game_name".srm "$gambatte_dir"/"$game_name".srm
cp "$destination_dir"/"$game_name".rtc "$gambatte_dir"/"$game_name".rtc
sync
