#!/bin/sh

source_dir="/mnt/SDCARD/Saves/RA_saves/TGB Dual/.netplay"
destination_dir="/mnt/SDCARD/Saves/RA_saves/TGB Dual"
tgb_dual_config="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.opt"
tgb_dual_config_p1="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.p1"
backup_config="/mnt/SDCARD/RetroArch/.retroarch/config/TGB Dual/TGB Dual.backup"

if [ ! -f "$backup_config" ]; then
    cp "$tgb_dual_config" "$backup_config"
	cp "$tgb_dual_config_p1" "$tgb_dual_config"
	sync
fi

for file in "$destination_dir"/*; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            cp "$file" "$destination_dir/client-$filename"
			sync
        fi
    done

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/

file_name=$(basename "$1")

client_file="/mnt/SDCARD/Roms/GB/client-$file_name"

cp "$1" "$client_file"
sync

LD_PRELOAD=/mnt/SDCARD/Koriki/lib/libpadsp.so /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/tgbdual_libretro.so --subsystem "gb_link_2p" "$1" "$client_file"

rm -f "$destination_dir"/client-*
sync

cp "$backup_config" "$tgb_dual_config"
rm "$backup_config"
sync

rm -f "$client_file"
sync

