#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`

if [ "$runsvr" != "0" ] ; then
    FILE=/customer/app/axp_test

    if [ -f "$FILE" ]; then
        killall audioserver
		killall audioserver.plu
		/customer/app/tinymix set 6 0
		vol=`/customer/app/jsonval vol`
		vol=`expr 41 + 63 \ $vol \ 20`
		/customer/app/tinymix set 6 $vol
    else
        killall audioserver
		killall audioserver.min
    fi
fi

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
LD_PRELOAD=/customer/lib/libpadsp.so /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/fbneo_libretro.so "$1"

runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
	/mnt/SDCARD/Koriki/bin/audioserver &
	if [ -f /customer/lib/libpadsp.so ]; then
		export LD_PRELOAD=/customer/lib/libpadsp.so
	fi
fi
