#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`

if [ "$runsvr" != "0" ] ; then
	FILE=/customer/app/axp_test

    if [ -f "$FILE" ]; then
        killall audioserver
		killall audioserver.plu
		FILE2=/tmp/audioserver_on
		if [ -f "$FILE2" ]; then
			rm /tmp/audioserver_on
			/customer/app/sysmon freemma
		fi
    else
        killall audioserver
		killall audioserver.min
    fi
fi

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/
LD_PRELOAD=/customer/lib/libpadsp.so /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/pcsx_rearmed_libretro_old.so "$1"

runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
	FILE=/customer/app/axp_test
	if [ -f "$FILE" ]; then
	touch /tmp/audioserver_on
	fi
	/mnt/SDCARD/Koriki/bin/audioserver &
	if [ -f /customer/lib/libpadsp.so ]; then
		export LD_PRELOAD=/customer/lib/libpadsp.so
	fi
fi
