#!/bin/sh

runsvr=`/customer/app/jsonval audiofix`

if [ "$runsvr" != "0" ] ; then
    FILE=/customer/app/axp_test

    if [ -f "$FILE" ]; then
        killall audioserver
		killall audioserver.plu
    else
        killall audioserver
		killall audioserver.min
    fi
fi

cd /mnt/SDCARD/RetroArch/
HOME=/mnt/SDCARD/RetroArch/ /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/prboom_libretro.so "$1"

runsvr=`/customer/app/jsonval audiofix`
if [ "$runsvr" != "0" ] ; then
	/mnt/SDCARD/Koriki/bin/audioserver &
	if [ -f /customer/lib/libpadsp.so ]; then
		export LD_PRELOAD=/customer/lib/libpadsp.so
	fi
fi
